version: 1.0.{build}

max_jobs: 2

image:
- Ubuntu2204
- Visual Studio 2022

configuration:
- Release

before_build:
- sh: sudo apt-get update
- sh: sudo apt-get install -y libx11-dev
- sh: sudo apt-get install -y libgl1-mesa-dev
- sh: sudo apt-get install -y g++-12
- sh: sudo apt-get install -y gcc-12
- git submodule update --init --recursive
- cmd: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
- sh: cmake -H. -Bbuild -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Release

build_script:
- cd build
- cmake --build . --config Release